/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-12 04:01:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>우리 둘만의 사잇길</title>\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"resources/css/main.css\" />\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t#banner {\r\n");
      out.write("\t\t\t\tdisplay: -ms-flexbox;\r\n");
      out.write("\t\t\t\t-ms-flex-pack: center;\r\n");
      out.write("\t\t\t\t-ms-flex-align: center;\r\n");
      out.write("\t\t\t\tpadding: 0em 0em 0em 0em;\r\n");
      out.write("\t\t\t\t-moz-align-items: center;\r\n");
      out.write("\t\t\t\t-webkit-align-items: center;\r\n");
      out.write("\t\t\t\t-ms-align-items: center;\r\n");
      out.write("\t\t\t\talign-items: center;\r\n");
      out.write("\t\t\t\tdisplay: -moz-flex;\r\n");
      out.write("\t\t\t\tdisplay: -webkit-flex;\r\n");
      out.write("\t\t\t\tdisplay: -ms-flex;\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\t-moz-justify-content: center;\r\n");
      out.write("\t\t\t\t-webkit-justify-content: center;\r\n");
      out.write("\t\t\t\t-ms-justify-content: center;\r\n");
      out.write("\t\t\t\tjustify-content: center;\t\t\t\r\n");
      out.write("\t\t\t\tbackground-image: url(\"resources/images/mainImage.jpg\");\r\n");
      out.write("\t\t\t\tbackground-position: center;\r\n");
      out.write("\t\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\t\tborder-top: 0;\r\n");
      out.write("\t\t\t\tmin-height: 100vh;\r\n");
      out.write("\t\t\t\theight: 100vh !important;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Banner -->\r\n");
      out.write("\t\t\t<section id=\"banner\">\r\n");
      out.write("\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t<h1 id=\"mainFont\" style=\"display:inline\">Sait Gil</h1>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-family:'Noto Serif KR'; font-size: 20px; margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t사잇길에 오신 것을 환영합니다. <br>\r\n");
      out.write("\t\t\t\t\t\t\t프라이빗 채팅 및 다양한 서비스로 연인과의 추억을 쌓으세요. \r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/login.me\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"userId\"  name=\"userId\" placeholder=\"ID를 입력하세요.\" style=\"background-color:white; width:35%; display:inline !important\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"userPwd\" name=\"userPwd\" placeholder=\"비밀번호를 입력하세요.\" style=\"display:inline !important; background-color:white; width:35%\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"button big scrolly\" value=\"LOGIN\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<a href=\"views/member/agreePage.jsp\" style=\"color:white;  font-weight: lighter; display: inline !important\">SignUp</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"views/member/memberSearch.jsp\" style=\"color:white; font-weight: lighter; display: inline !important; margin: 20px;\">Forgotten Account</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"views/member/invitationPage.jsp\">connectTest</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//로그인 \r\n");
      out.write("\t\t\t\tfunction validate() {  \r\n");
      out.write("\t\t\t\t\tif($('#userId').val().trim().length == 0 ){\r\n");
      out.write("\t\t\t\t\t\talert('아이디를 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t\t$('#userId').focus();\r\n");
      out.write("\t\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($('#userPwd').val().trim().length == 0){\r\n");
      out.write("\t\t\t\t\t\talert('비밀번호를 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t\t$('#userPwd').focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\ttrue;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("\t\t\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t\t\t<section class=\"wrapper style1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 2 Columns -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"flex flex-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col col1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"image round fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"generic.html\" class=\"link\"><img src=\"resources/images/pic01.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col col2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3 style=\"font-family:'Do Hyeon'; color: #e23a6e; font-weight:200;\">우리의 달콤한 추억 저장소, 사잇길</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"font-family:'Noto Serif KR'; font-size: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t지금 연애하고 계신가요? <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t사잇길에서 프라이빗 채팅 및 다양한 서비스를 통해 연인과의 소중한 추억을 저장하세요. <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t복잡한 커플앱들은 안녕~! <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t기존의 커플들을 위한 앱-웹의 서비스들을 한 곳에서 편리하게 즐기실 수 있습니다! \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p style=\"font-family:'Noto Serif KR'; font-size: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t사잇길은 연인과 더 사랑스럽게 소통하고, 소중한 추억을 간편하게 저장할 수 있는 공간입니다. \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button\">Let's Start</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t\t\t<section class=\"wrapper style2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flex flex-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col col2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 style=\"font-family:'Do Hyeon'; color:#e23a6e; font-weight:200;\">사잇길의 다양한 기능을 즐겨보세요!</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>사랑스런 둘만의 대화</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>소중한 추억 앨범</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>특별한 기념일</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>함께 쓰는 캘린더 </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>함께 달성할 버킷리스트</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>실제 커플들이 공유하는 커뮤니티</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>연인과의 친밀도와 유대감을 높혀줄 스토어</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"button\">Let's Start</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col col1 first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image round fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"generic.html\" class=\"link\"><img src=\"resources/images/pic02.jpg\"/></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Section -->\r\n");
      out.write("\t\t\t\t\t<section class=\"wrapper style1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t\t\t\t<header class=\"align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color:#e23a6e; font-family: Noto Serif KR\">Created By</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <p>Cras sagittis turpis sit amet est tempus, sit amet consectetur purus tincidunt.</p> -->\r\n");
      out.write("\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flex flex-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image round fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/team1.png\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>최 영근</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image round fit team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/team5.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>한 미선</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"image round fit team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/team2.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>김 성은</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"flex flex-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"image round fit team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/team3.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>손 권모</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h1 style=\"display:inline; line-height: 270px; font-size:70px; font-family: 'Great Vibes'; color:#fa96b5\">Sait Gil</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col align-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"image round fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"resources/images/team4.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>유 현규</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon fa-snapchat\"><span class=\"label\">Snapchat</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<p>&copy; Untitled. All rights reserved. Design: <a href=\"https://templated.co\">TEMPLATED</a>. Images: <a href=\"https://unsplash.com\">Unsplash</a>.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/js/jquery.scrolly.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/js/skel.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
