/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-12 05:12:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("   \r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/css/joinSearchForm.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"@import url('https://fonts.googleapis.com/css?family=Dancing+Script|Great+Vibes&display=swap');\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tbackground-image: url(\"../../resources/images/mainImage.jpg\");\r\n");
      out.write("\t\t\tbackground-position: center;\r\n");
      out.write("\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t</style>    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("\">Sait Gil</a>\r\n");
      out.write("    </header> \r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"signup-form\">\r\n");
      out.write("                    <form id=\"joinForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/insert.me\" method=\"post\" onsubmit=\"return joinValidate();\" class=\"register-form\" >\r\n");
      out.write("                        <br><br>\r\n");
      out.write("                        <h1>사잇길 회원가입</h1>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"name\">* Name :</label>\r\n");
      out.write("                                <input type=\"text\" maxlength=\"13\" name=\"userName\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"ID\">* ID :</label>\r\n");
      out.write("                                <input type=\"text\" name=\"userId\" id=\"userId\" style=\"width:80%; display:inline\" required>\r\n");
      out.write("                                <input type=\"submit\" class=\"submit\" id=\"idCheck\" value=\"ID check\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"password\">* Password : </label>\r\n");
      out.write("                                <input type=\"password\"  maxlength=\"15\" name=\"userPwd\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"confirmPassword\">* Confirm Password : </label>\r\n");
      out.write("                                <input type=\"password\"  maxlength=\"15\" name=\"userPwd2\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"phone\">* Phone Number : </label>\r\n");
      out.write("                                <input type=\"tel\" maxlength=\"11\" name=\"phone\" placeholder=\"(-없이)01012345678\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\">* Email ID :</label>\r\n");
      out.write("                                <input type=\"email\" name=\"email\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"address\">Address :</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"address\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-radio\">\r\n");
      out.write("                            <label for=\"gender\" class=\"radio-label\">Gender :</label>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"gender\" id=\"M\" value=\"M\">\r\n");
      out.write("                                <label for=\"M\">Male</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"gender\" id=\"F\" value=\"F\">\r\n");
      out.write("                                <label for=\"F\">Female</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"birth_date\">Birth Of Date :</label>\r\n");
      out.write("                            <input type=\"date\" name=\"birth\" id=\"birth\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-submit\">\r\n");
      out.write("                        \t<input type=\"button\" value=\"뒤로가기\" class=\"submit\" id=\"back\" onclick=\"goBack();\" />\r\n");
      out.write("                            <input type=\"reset\" value=\"초기화\" class=\"submit\" name=\"reset\" id=\"reset\" />\r\n");
      out.write("                            <input type=\"submit\" value=\"회원가입\" class=\"submit\" name=\"submit\" id=\"submit\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\tfunction goBack() {\r\n");
      out.write("\t\thistory.back();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction joinValidate() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//이름 검사( 2글자 이상 )\r\n");
      out.write("\t\tif(!(/^[가-힣]{2,}$/.test($(\"#joinForm input[name=userName]\").val()))) {\r\n");
      out.write("\t\t\t$(\"#joinForm input[name=userName]\").focus();\r\n");
      out.write("\t\t\talert(\"이름 오류\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t//아이디 검사 총 4~12글자(대문자 포함)\r\n");
      out.write("\t\tif(!(/^[a-z][a-z\\d]{3,11}$/i.test($(\"#joinForm input[name=userId]\").val()))) {\r\n");
      out.write("\t\t\t$(\"#joinForm input[name=userId]\").focus() \r\n");
      out.write("\t\t\talert(\"아이디값 오류\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호와 비밀번호 확인 일치하기 \r\n");
      out.write("\t\tif($(\"#joinForm input[name=userPwd]\").val() != $(\"#joinForm input[name=userPwd2]\").val()) {\r\n");
      out.write("\t\t\talert(\"비번 오류\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert($(\"#joinForm input[name=birth]\").val());\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
