/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-13 02:05:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/menubar.jsp", Long.valueOf(1565590646682L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");
	

      out.write("    \r\n");

	String birthday = loginUser.getBirth();
	String pBirthday = loginUser.getPartnerBirth();
	String result ="";
	String pResult=""; 

	if(birthday == null || birthday == "") {
	    result = "입력된 값이 없습니다.";
	 } else {
	
		 if(birthday.charAt(5) == '0') {
		    if(birthday.charAt(8) == 0) {
		       result = birthday.charAt(6) + "월 " + birthday.charAt(9) + "일";
		    }else {
		       result = birthday.charAt(6) + "월 " + birthday.substring(8,10) + "일";
		    }
		 }else {
		    if(birthday.charAt(8) == 0) {
		       result = birthday.substring(5,7) + "월 " + birthday.charAt(9) + "일";
		    }else {
		       result = birthday.substring(5,7) + "월 " + birthday.substring(8,10) + "일";
		    }
		 }
	}
	if(pBirthday == null || pBirthday == "") {
	    pResult = "입력된 값이 없습니다.";
	 } else {
	
		 if(pBirthday.charAt(5) == '0') {
		    if(pBirthday.charAt(8) == 0) {
		       pResult = pBirthday.charAt(6) + "월 " + pBirthday.charAt(9) + "일";
		    }else {
		       pResult = pBirthday.charAt(6) + "월 " + pBirthday.substring(8,10) + "일";
		    }
		 }else {
		    if(pBirthday.charAt(8) == 0) {
		       pResult = pBirthday.substring(5,7) + "월 " + pBirthday.charAt(9) + "일";
		    }else {
		       pResult = pBirthday.substring(5,7) + "월 " + pBirthday.substring(8,10) + "일";
		    }
		 }
	}
	
    Calendar cal = Calendar.getInstance();
    Calendar cal2 = Calendar.getInstance();
    Calendar cal3 = Calendar.getInstance();
    Calendar today = Calendar.getInstance();
	
    String start = "2017-01-01";
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Date startDate = null;

    try {         
       startDate = sdf.parse(start);

    } catch (ParseException e) {
       e.printStackTrace();

    }
    
    cal.setTime(startDate);
    cal2.setTime(startDate);
    cal3.setTime(startDate);
    
    int day = 100;
    int dday = (int)((today.getTimeInMillis()-cal.getTimeInMillis())/(1000*60*60*24)+1);
    while(dday > day) {
       day +=100;
    }
    
    cal2.add(Calendar.DATE, day-1);
    cal3.add(Calendar.DATE, day+99);
    int year = (int)(((today.getTimeInMillis()-cal.getTimeInMillis())/(1000*60*60*24)+1)/365)+1;
    
    cal.add(Calendar.YEAR, year);
    
    String anivDate = sdf.format(cal.getTime());
    String dDate1 = sdf.format(cal2.getTime());
    String dDate2 = sdf.format(cal3.getTime());
    
    long anivDay = ((cal.getTimeInMillis()-today.getTimeInMillis())/(1000*60*60*24)+1);
    long dDay1 = ((cal2.getTimeInMillis()-today.getTimeInMillis())/(1000*60*60*24)+1);
    long dDay2 = ((cal3.getTimeInMillis()-today.getTimeInMillis())/(1000*60*60*24)+1);
    


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t<title>우리 둘만의 사잇길</title>\r\n");
      out.write("\t<link href=\"resources/css/menubar.css\" rel=\"stylesheet\" type=\"text/css\">\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \t <aside id=\"profile-1\" class=\"profileSide\"> \r\n");
      out.write("            <a href=\"#\"><img src=\"resources/images/profile_boy.png\" id=\"photo1\" class=\"profile\"></a>\r\n");
      out.write("            <span id=\"myName\">");
      out.print( loginUser.getUserName() );
      out.write("</span> ♥\r\n");
      out.write("\t\t\t<p id=\"myBirthDay\">");
      out.print( result );
      out.write("</p>\r\n");
      out.write("\t\t\t<table id=\"menuTB\"\t>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/icons/myPage2.png\" class=\"icon\" onclick=\"goMyPage();\"></th>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"resources/images/icons/calendar2.png\" class=\"icon\"></th>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"resources/images/icons/store2.png\" class=\"icon\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>마이페이지</td>\r\n");
      out.write("\t\t\t\t\t<td>캘린더</td>\r\n");
      out.write("\t\t\t\t\t<td>스토어</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"resources/images/icons/gallery2.png\" class=\"icon\"></th>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"resources/images/icons/saving3.png\" class=\"icon\"></th>\r\n");
      out.write("\t\t\t\t\t<th><img src=\"resources/images/icons/sns2.png\" class=\"icon\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>사진첩</td>\r\n");
      out.write("\t\t\t\t\t<td>가계부</td>\r\n");
      out.write("\t\t\t\t\t<td>SNS</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"help\">\r\n");
      out.write("\t\t\t\t<img src=\"resources/images/icons/help3.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t문의하기\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("        <aside id=\"profile-2\" class=\"profileSide\">\r\n");
      out.write("\t\t\t<div id=\"logout\" onclick=\"logout();\">\r\n");
      out.write("\t\t\t\tLOGOUT\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <a href=\"#\"><img src=\"resources/images/profile_girl.png\" id=\"photo2\" class=\"profile\"></a>\t\r\n");
      out.write("            ♥ <span id=\"partnerName\">");
      out.print( loginUser.getPartnerName() );
      out.write("</span>\r\n");
      out.write("            <p id=\"partnerBirthDay\">");
      out.print( pResult );
      out.write("</p>\r\n");
      out.write("\t\t\t<p id=\"firstDate\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table id=\"anniversary\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print( day );
      out.write("일</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"date1\" class=\"date\">");
      out.print( dDay1 );
      out.write("일 남음</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print( day+100 );
      out.write("일</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"date2\" class=\"date\">");
      out.print( dDay2 );
      out.write("일 남음</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print( year );
      out.write("주년</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"date3\" class=\"date\">");
      out.print( anivDay );
      out.write("일 남음</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("        </aside>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \tfunction goMyPage() {\r\n");
      out.write("        \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/myPage.me\";\r\n");
      out.write("        \t}\r\n");
      out.write("        \t\r\n");
      out.write("        \tfunction logout() {\r\n");
      out.write("        \t\tlocation.href = '");
      out.print( request.getContextPath() );
      out.write("/logout.me';\r\n");
      out.write("        \t}\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

	Member m = (Member)session.getAttribute("loginUser");  
	String[] gender = new String[2];
	switch(m.getGender()) {
		case "M" : gender[0] = "checked"; break;
		case "F" : gender[1] = "checked"; break;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/myPage.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tbackground-image: url(\"resources/images/mainImage.jpg\");\r\n");
      out.write("\t\t\tbackground-position: center;\r\n");
      out.write("\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\topacity:0.96;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("                <section class=\"signup-form\">\r\n");
      out.write("                    <form id=\"joinForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/update.me\" method=\"post\" onsubmit=\"return joinValidate();\" class=\"register-form\" >\r\n");
      out.write("                        <h1>마이페이지</h1>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            <span style=\"text-align: center;\">\r\n");
      out.write("                                <img src=\"resources/images/profile_boy.png\" id=\"myPhoto\" style=\"width:150px; height:150px;\"> \r\n");
      out.write("                                <input type=\"file\" style=\"border:none;\">\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div> \r\n");
      out.write("                            \t<table id=\"idTable\">\r\n");
      out.write("                            \t\t<tr> \r\n");
      out.write("                            \t\t\t<th colspan=\"2\" id=\"welcome\">");
      out.print( loginUser.getUserName() );
      out.write("님 사잇길에 오신 것을 환영합니다</th>\r\n");
      out.write("                            \t\t</tr>\r\n");
      out.write("                            \t\t<tr>\r\n");
      out.write("                            \t\t\t<th width=\"100px\"><label>Name : </label></th>\r\n");
      out.write("                            \t\t\t<th width=\"300px\"><label class=\"readonly\">");
      out.print( loginUser.getUserName() );
      out.write("</label></th>\r\n");
      out.write("                            \t\t</tr>\r\n");
      out.write("                            \t\t<tr>\r\n");
      out.write("                            \t\t\t<th><label>ID : </label></th>\r\n");
      out.write("                            \t\t\t<th><label class=\"readonly\">");
      out.print( loginUser.getUserId() );
      out.write("</label></th>\r\n");
      out.write("                            \t\t</tr>\r\n");
      out.write("                            \t</table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-row\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"userPwd\">Password : </label>\r\n");
      out.write("                                <input type=\"password\" name=userPwd maxlength=\"15\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"confirmPassword\">Confirm Password : </label>\r\n");
      out.write("                                <input type=\"password\" name=\"userPwd2\" maxlength=\"15\" required >\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"submit\" class=\"submit\" id=\"changePwd\" value=\"Change\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"phone\">Phone Number : </label>\r\n");
      out.write("                                <input type=\"number\" name=\"phone\" value=\"");
      out.print( loginUser.getPhone() );
      out.write("\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\">Email ID :</label>\r\n");
      out.write("                                <input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.print( loginUser.getEmail() );
      out.write("\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"address\">Address :</label>\r\n");
      out.write("                                    <input type=\"text\" name=\"address\" value=\"");
      out.print( loginUser.getAddress() );
      out.write("\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"form-radio\">\r\n");
      out.write("                            <label for=\"gender\" class=\"radio-label\">Gender :</label>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"gender\" id=\"M\" value=\"M\" ");
      out.print( gender[0] );
      out.write(">\r\n");
      out.write("                                <label for=\"M\">Male</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-radio-item\">\r\n");
      out.write("                                <input type=\"radio\" name=\"gender\" id=\"F\" value=\"F\" ");
      out.print( gender[1] );
      out.write(">\r\n");
      out.write("                                <label for=\"F\">Female</label>\r\n");
      out.write("                                <span class=\"check\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"birth_date\">Birth Of Date :</label>\r\n");
      out.write("                            <input type=\"date\" name=\"birth\" id=\"birth\" value=");
      out.print( loginUser.getBirth() );
      out.write(">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-submit\">\r\n");
      out.write("                        \t<input type=\"button\" value=\"Back\" class=\"submit\" id=\"back\" onclick=\"goBack();\" />\r\n");
      out.write("                            <input type=\"reset\" value=\"Disconnect\" class=\"submit\" id=\"disconnect\" onclick=\"disconnect();\" />\r\n");
      out.write("                            <input type=\"submit\" value=\"Save\" class=\"submit\" name=\"submit\" id=\"submit\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("    \tfunction goBack() {\r\n");
      out.write("    \t\thistory.back();\r\n");
      out.write("    \t}\r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
